version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu1804
clone_depth: 1
install:
- sh: >-
    sudo apt-get update

    sudo apt-get install --yes g++ cmake make
build_script:
- sh: >-
    git submodule update --init --recursive

    mkdir build

    cd build

    cmake ..

    cmake --build .
