os: linux

dist: bionic

language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    packages:
      - linux-libc-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

