name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get -y install g++ cmake make linux-libc-dev
    - name: Fetch Git submodules
      run: git submodule update --init --recursive
    - name: Run build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
